-- HAIR ARTISANS - COMPLETE SUPABASE SETUP / REPAIR SCRIPT
-- Run this entire file in Supabase SQL Editor.
-- It does not delete existing bookings.

create extension if not exists pgcrypto;

-- ============================================================
-- ADMIN USERS
-- ============================================================
create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

-- ============================================================
-- CUSTOMERS
-- ============================================================
create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  phone text not null,
  email text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.customers add column if not exists email text;
alter table public.customers add column if not exists created_at timestamptz not null default now();
alter table public.customers add column if not exists updated_at timestamptz not null default now();

create index if not exists customers_phone_idx on public.customers(phone);
create index if not exists customers_email_idx on public.customers(email);

-- ============================================================
-- SERVICES
-- ============================================================
create table if not exists public.services (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric(10,2) not null default 0,
  duration_minutes integer not null default 30,
  category text,
  image_url text,
  image_path text,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.services add column if not exists description text;
alter table public.services add column if not exists category text;
alter table public.services add column if not exists image_url text;
alter table public.services add column if not exists image_path text;
alter table public.services add column if not exists active boolean not null default true;
alter table public.services add column if not exists sort_order integer not null default 0;
alter table public.services add column if not exists duration_minutes integer not null default 30;
alter table public.services add column if not exists created_at timestamptz not null default now();
alter table public.services add column if not exists updated_at timestamptz not null default now();

-- ============================================================
-- BOOKINGS
-- ============================================================
create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  customer_id uuid not null references public.customers(id) on delete restrict,
  service_id bigint not null references public.services(id) on delete restrict,
  appointment_date date not null,
  start_time time not null,
  end_time time not null,
  status text not null default 'pending',
  payment_status text not null default 'pending',
  service_price numeric(10,2),
  deposit_amount numeric(10,2) not null default 0,
  balance_amount numeric(10,2) not null default 0,
  payment_reference text,
  confirmation_sent boolean not null default false,
  payment_notification_sent boolean not null default false,
  reminder_sent boolean not null default false,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.bookings add column if not exists payment_status text default 'pending';
alter table public.bookings add column if not exists service_price numeric(10,2);
alter table public.bookings add column if not exists deposit_amount numeric(10,2) not null default 0;
alter table public.bookings add column if not exists balance_amount numeric(10,2) not null default 0;
alter table public.bookings add column if not exists payment_reference text;
alter table public.bookings add column if not exists confirmation_sent boolean not null default false;
alter table public.bookings add column if not exists payment_notification_sent boolean not null default false;
alter table public.bookings add column if not exists reminder_sent boolean not null default false;
alter table public.bookings add column if not exists notes text;
alter table public.bookings add column if not exists created_at timestamptz not null default now();
alter table public.bookings add column if not exists updated_at timestamptz not null default now();

create index if not exists bookings_date_idx on public.bookings(appointment_date);
create index if not exists bookings_date_time_idx on public.bookings(appointment_date, start_time);
create index if not exists bookings_customer_idx on public.bookings(customer_id);

-- ============================================================
-- OUR WORK / GALLERY
-- ============================================================
create table if not exists public.gallery_items (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  image_url text not null,
  image_path text not null,
  is_published boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.gallery_items add column if not exists description text;
alter table public.gallery_items add column if not exists image_url text;
alter table public.gallery_items add column if not exists image_path text;
alter table public.gallery_items add column if not exists is_published boolean not null default true;
alter table public.gallery_items add column if not exists sort_order integer not null default 0;
alter table public.gallery_items add column if not exists created_at timestamptz not null default now();
alter table public.gallery_items add column if not exists updated_at timestamptz not null default now();

create index if not exists gallery_items_published_idx on public.gallery_items(is_published, sort_order);

-- Seed the 14 supplied local work photos only when the gallery table is empty.
-- These can be renamed, hidden or deleted from Admin → Our Work.
insert into public.gallery_items (title, description, image_url, image_path, is_published, sort_order)
select
  'Hair Artisans Work ' || lpad(n::text, 2, '0'),
  null,
  '/images/gallery/gallery-' || lpad(n::text, 2, '0') || '.jpeg',
  'local/gallery-' || lpad(n::text, 2, '0') || '.jpeg',
  true,
  n
from generate_series(1, 14) as n
where not exists (select 1 from public.gallery_items);

-- ============================================================
-- HOMEPAGE SETTINGS
-- ============================================================
create table if not exists public.site_settings (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

insert into public.site_settings(key, value)
values ('hero_image_url', '/images/hero.jpg')
on conflict (key) do nothing;

-- ============================================================
-- ADMIN CHECK FUNCTION
-- ============================================================
create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public, pg_catalog
stable
as $$
  select exists (
    select 1
    from public.admin_users
    where user_id = auth.uid()
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

-- ============================================================
-- AVAILABILITY FUNCTION
-- ============================================================
drop function if exists public.get_booked_times(date);

create or replace function public.get_booked_times(p_appointment_date date)
returns table(start_time time, end_time time)
language sql
security definer
set search_path = public, pg_catalog
stable
as $$
  select b.start_time, b.end_time
  from public.bookings b
  where b.appointment_date = p_appointment_date
    and lower(b.status::text) in ('pending', 'confirmed')
  order by b.start_time;
$$;

revoke all on function public.get_booked_times(date) from public;
grant execute on function public.get_booked_times(date) to anon, authenticated;

-- ============================================================
-- FREE PUBLIC BOOKING FUNCTION
-- ============================================================
drop function if exists public.create_hair_artisans_booking(text,text,text,text,bigint,date,time without time zone);

create or replace function public.create_hair_artisans_booking(
  p_full_name text,
  p_phone text,
  p_email text,
  p_notes text,
  p_service_id bigint,
  p_appointment_date date,
  p_start_time time
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_catalog
as $$
declare
  v_customer_id uuid;
  v_service_price numeric(10,2);
  v_duration integer;
  v_end_time time;
  v_booking_id bigint;
  v_today date;
begin
  p_full_name := btrim(coalesce(p_full_name, ''));
  p_phone := btrim(coalesce(p_phone, ''));
  p_email := nullif(btrim(coalesce(p_email, '')), '');
  p_notes := nullif(btrim(coalesce(p_notes, '')), '');

  if length(p_full_name) < 2 then
    raise exception 'Please enter your full name.' using errcode = '22023';
  end if;

  if length(regexp_replace(p_phone, '[^0-9+]', '', 'g')) < 7 then
    raise exception 'Please enter a valid phone number.' using errcode = '22023';
  end if;

  if p_appointment_date is null or p_start_time is null then
    raise exception 'Please select a date and time.' using errcode = '22023';
  end if;

  v_today := (now() at time zone 'Africa/Johannesburg')::date;

  if p_appointment_date < v_today then
    raise exception 'The selected date has already passed.' using errcode = '22023';
  end if;

  if p_appointment_date > v_today + 60 then
    raise exception 'The selected date is outside the booking window.' using errcode = '22023';
  end if;

  if extract(dow from p_appointment_date) in (1, 2) then
    raise exception 'The shop is closed on Monday and Tuesday.' using errcode = '22023';
  end if;

  if p_start_time < time '09:00' or p_start_time >= time '17:00' then
    raise exception 'The selected time is outside business hours.' using errcode = '22023';
  end if;

  if extract(minute from p_start_time)::integer % 30 <> 0
     or extract(second from p_start_time) <> 0 then
    raise exception 'Please select a 30-minute booking slot.' using errcode = '22023';
  end if;

  select s.price, s.duration_minutes
    into v_service_price, v_duration
  from public.services s
  where s.id = p_service_id
    and s.active = true;

  if not found then
    raise exception 'The selected service is not available.' using errcode = '22023';
  end if;

  if v_duration is null or v_duration <= 0 then
    raise exception 'The selected service has an invalid duration.' using errcode = '22023';
  end if;

  v_end_time := p_start_time + make_interval(mins => v_duration);

  if v_end_time > time '17:00' then
    raise exception 'That service cannot finish before closing time.' using errcode = '22023';
  end if;

  -- Prevent two customers from taking an overlapping slot at the same time.
  perform pg_advisory_xact_lock(hashtext('hair-artisans-booking-' || p_appointment_date::text));

  if exists (
    select 1
    from public.bookings b
    where b.appointment_date = p_appointment_date
      and lower(b.status::text) in ('pending', 'confirmed')
      and b.start_time < v_end_time
      and b.end_time > p_start_time
  ) then
    raise exception 'That time is no longer available.' using errcode = '23P01';
  end if;

  select c.id
    into v_customer_id
  from public.customers c
  where regexp_replace(c.phone, '[^0-9+]', '', 'g') = regexp_replace(p_phone, '[^0-9+]', '', 'g')
  order by c.updated_at desc nulls last, c.created_at desc
  limit 1;

  if v_customer_id is null then
    insert into public.customers(full_name, phone, email)
    values (p_full_name, p_phone, p_email)
    returning id into v_customer_id;
  else
    update public.customers
    set full_name = p_full_name,
        phone = p_phone,
        email = p_email,
        updated_at = now()
    where id = v_customer_id;
  end if;

  insert into public.bookings(
    customer_id,
    service_id,
    appointment_date,
    start_time,
    end_time,
    status,
    service_price,
    deposit_amount,
    balance_amount,
    notes,
    created_at,
    updated_at
  )
  values (
    v_customer_id,
    p_service_id,
    p_appointment_date,
    p_start_time,
    v_end_time,
    'confirmed',
    v_service_price,
    0,
    coalesce(v_service_price, 0),
    p_notes,
    now(),
    now()
  )
  returning id into v_booking_id;

  return v_booking_id;
end;
$$;

revoke all on function public.create_hair_artisans_booking(text,text,text,text,bigint,date,time without time zone) from public;
grant execute on function public.create_hair_artisans_booking(text,text,text,text,bigint,date,time without time zone) to anon, authenticated;

-- ============================================================
-- RLS POLICIES
-- ============================================================
alter table public.admin_users enable row level security;
alter table public.customers enable row level security;
alter table public.services enable row level security;
alter table public.bookings enable row level security;
alter table public.gallery_items enable row level security;
alter table public.site_settings enable row level security;

drop policy if exists admin_users_self_select on public.admin_users;
create policy admin_users_self_select on public.admin_users
for select to authenticated
using (user_id = auth.uid());

drop policy if exists services_public_read_active on public.services;
create policy services_public_read_active on public.services
for select to anon, authenticated
using (active = true or public.is_admin());

drop policy if exists services_admin_all on public.services;
create policy services_admin_all on public.services
for all to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists gallery_public_read_published on public.gallery_items;
create policy gallery_public_read_published on public.gallery_items
for select to anon, authenticated
using (is_published = true or public.is_admin());

drop policy if exists gallery_admin_all on public.gallery_items;
create policy gallery_admin_all on public.gallery_items
for all to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists site_settings_public_read on public.site_settings;
create policy site_settings_public_read on public.site_settings
for select to anon, authenticated
using (key = 'hero_image_url');

drop policy if exists site_settings_admin_all on public.site_settings;
create policy site_settings_admin_all on public.site_settings
for all to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists customers_admin_all on public.customers;
create policy customers_admin_all on public.customers
for all to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists bookings_admin_all on public.bookings;
create policy bookings_admin_all on public.bookings
for all to authenticated
using (public.is_admin())
with check (public.is_admin());

-- ============================================================
-- STORAGE BUCKET
-- ============================================================
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'hair-artisan-images',
  'hair-artisan-images',
  true,
  5242880,
  array['image/jpeg','image/png','image/webp']::text[]
)
on conflict (id) do update
set public = true,
    file_size_limit = 5242880,
    allowed_mime_types = array['image/jpeg','image/png','image/webp']::text[];

alter table storage.objects enable row level security;

drop policy if exists hair_artisan_images_public_read on storage.objects;
create policy hair_artisan_images_public_read on storage.objects
for select to anon, authenticated
using (bucket_id = 'hair-artisan-images');

drop policy if exists hair_artisan_images_admin_insert on storage.objects;
create policy hair_artisan_images_admin_insert on storage.objects
for insert to authenticated
with check (
  bucket_id = 'hair-artisan-images'
  and public.is_admin()
  and (storage.foldername(name))[1] in ('services','gallery','site')
);

drop policy if exists hair_artisan_images_admin_update on storage.objects;
create policy hair_artisan_images_admin_update on storage.objects
for update to authenticated
using (bucket_id = 'hair-artisan-images' and public.is_admin())
with check (bucket_id = 'hair-artisan-images' and public.is_admin());

drop policy if exists hair_artisan_images_admin_delete on storage.objects;
create policy hair_artisan_images_admin_delete on storage.objects
for delete to authenticated
using (bucket_id = 'hair-artisan-images' and public.is_admin());

-- ============================================================
-- CLIENT GRANTS
-- ============================================================
grant usage on schema public to anon, authenticated;
grant select on public.services to anon, authenticated;
grant select on public.gallery_items to anon, authenticated;
grant select on public.site_settings to anon, authenticated;
grant select, insert, update, delete on public.services to authenticated;
grant select, insert, update, delete on public.gallery_items to authenticated;
grant select, insert, update, delete on public.site_settings to authenticated;
grant select, insert, update, delete on public.customers to authenticated;
grant select, insert, update, delete on public.bookings to authenticated;
grant select on public.admin_users to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- ============================================================
-- ADMIN USER
-- ============================================================
-- Run this separately after replacing the email with the email of your
-- Supabase Auth account used for the Hair Artisans admin login:
--
-- insert into public.admin_users(user_id)
-- select id from auth.users where email = 'YOUR-ADMIN-EMAIL'
-- on conflict (user_id) do nothing;
